#! /usr/bin/env bash

set -euo pipefail
shopt -s inherit_errexit
shopt -s expand_aliases

main() {
  local -a results=()
  results+=($(git ls-files -om --exclude-standard))
  if [[ "${#results[@]}" == 0 ]]; then
    exit 0
  fi
  exec gum filter --no-limit "${results[@]}"
}

main
